name: Generate Fortune and Save

on:
  schedule:
    - cron: "0 0 * * *" # Runs every hour
  workflow_dispatch: # Allows manual triggering
  
permissions:
  contents: write

jobs:
  generate-fortune:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install cowsay and fortune
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cowsay fortune

    # Step 3: Generate a fortune and save it to a file
    - name: Generate fortune and save output
      run: |
        mkdir -p data/fortunes
        fortune | cowsay > `date + "data/fortunes/%Y%m%d_%H%M%S.txt"`       

    # Step 4: Commit and push changes
    - name: Configure Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Adding today's fortune!"
        git push
      env:
        # Ensure permissions for pushing changes
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
